// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DisplayCard: typeof import('./components/DisplayCard.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    HelpModal: typeof import('./components/HelpModal.vue')['default']
    Loading: typeof import('./components/Loading.vue')['default']
    README: typeof import('./components/README.md')['default']
    RecruitCalculator: typeof import('./components/RecruitCalculator.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Switch: typeof import('./components/Switch.vue')['default']
    TagCombobox: typeof import('./components/TagCombobox.vue')['default']
  }
}

export {}
